## Some Linear Algebra

In [2]:
import numpy as np
import math

In [4]:
A = np.array([[1, 2, 1],
              [4, 4, 5],
              [6, 7, 7]])
A

array([[1, 2, 1],
       [4, 4, 5],
       [6, 7, 7]])

Taking the determinant of A (may not exist)

In [9]:
np.linalg.det(A)

1.0000000000000018

If there is a determinant, the matrix is regular / invertible, or "nonsingular", and there is a unique inverse, A to the -1.

In [12]:
A

array([[1, 2, 1],
       [4, 4, 5],
       [6, 7, 7]])

In [8]:
np.linalg.inv(A)

array([[-7., -7.,  6.],
       [ 2.,  1., -1.],
       [ 4.,  5., -4.]])

In this case, it seems like

The last row of A, c(i, j, k) becomes the first row of A(-1): -c(k), -c(j), c(i).

The second row of A, b(i, j, k) becomes the *third* row of A(-1): b(j), b(k), -b(i).

The third row of A, a(i, j, k) becomes the *second* row of A(-1): a(j), a(k), -a(i).

Transposing the matrix results in a new matrix where the 'columns' become the 'rows' and vice versa.

In [13]:
A.T

array([[1, 4, 6],
       [2, 4, 7],
       [1, 5, 7]])

Taking the inverse of the transposed matrix (If A is invertible, then so is A(T).)

In [15]:
trans_A = A.T
np.linalg.inv(trans_A)

array([[-7.,  2.,  4.],
       [-7.,  1.,  5.],
       [ 6., -1., -4.]])

Some matrices are called "symmetric".  In a symmetric matrix, A, A = A(T).

The sum of symmetric matrices is a symmetric matrix, however the product of two symmetric matrices is generally not symmetric.

In [39]:
S = np.array([[2, 0, 3],
              [0, 2, 0],
              [3, 0, 2]])
S

array([[2, 0, 3],
       [0, 2, 0],
       [3, 0, 2]])

In [40]:
trans_S = S.T
trans_S

array([[2, 0, 3],
       [0, 2, 0],
       [3, 0, 2]])

In [41]:
np.linalg.det(S)

-10.000000000000002

Since this matrix has a determinant, it is also invertible.

In [42]:
inv_S = np.linalg.inv(S)
inv_S

array([[-0.4,  0. ,  0.6],
       [ 0. ,  0.5,  0. ],
       [ 0.6,  0. , -0.4]])

In [43]:
inv_trans_S = np.linalg.inv(trans_S)
inv_trans_S

array([[-0.4,  0. ,  0.6],
       [ 0. ,  0.5,  0. ],
       [ 0.6,  0. , -0.4]])

Not surprisingly, when a matrix is equal to it's transpose, and the matrix is invertible, the inv. of its transpose it equal to its transpose.

Let's create a new symmetric matrix, R. What happens when we add it to or multiply it with our symmetric matrix, S?

In [54]:
R = np.array([[1, 2, 3],
              [2, 1, 2],
              [3, 2, 1]])

In [55]:
R.T

array([[1, 2, 3],
       [2, 1, 2],
       [3, 2, 1]])

In [56]:
SS = S + R
SS

array([[3, 2, 6],
       [2, 3, 2],
       [6, 2, 3]])

In [57]:
SS.T

array([[3, 2, 6],
       [2, 3, 2],
       [6, 2, 3]])

In [62]:
SS2 = S.dot(R)
SS2

array([[11, 10,  9],
       [ 4,  2,  4],
       [ 9, 10, 11]])

In [63]:
SS2.T

array([[11,  4,  9],
       [10,  2, 10],
       [ 9,  4, 11]])

In this case, both the result of addition and multiplication are also symmetric.

However, while all A + B are symmetric where A and B are symmetric, NOT ALL A * B are symmetric where A and B are symmetric.

### Multiplying a matrix by a constant

If we call the constant lambda, then multiplying by this constant *scales* the matrix by the constant lambda.

In [64]:
I =  np.ones((3,3))

In [65]:
I.dot(5)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [18]:
B = np.array([[1,2,3],
              [2,3,2],
              [1,2,1]])

In [66]:
B.dot(2)

array([[2, 4, 6],
       [4, 6, 4],
       [2, 4, 2]])

Addition of matrix and constant - straightforward.

In [60]:
I + 5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [61]:
B + 2

array([[3, 4, 5],
       [4, 5, 4],
       [3, 4, 3]])